# Generated by Django 4.2.8 on 2023-12-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('ano_fabricacao', models.IntegerField(max_length=4)),
                ('categoria', models.CharField(max_length=10)),
                ('nome_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.cliente')),
            ],
        ),
    ]
