# Generated by Django 5.0 on 2023-12-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('ano_fabricacao', models.IntegerField()),
                ('preco', models.FloatField(blank=True, default=0, null=True)),
                ('categoria', models.CharField(max_length=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('cpf_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.cliente')),
            ],
        ),
    ]
