# Generated by Django 4.2.8 on 2023-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano_fabricacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
