# Generated by Django 4.2.8 on 2023-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_carro_ano_fabricacao_alter_cliente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='placa',
        ),
        migrations.AddField(
            model_name='carro',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
