# Generated by Django 4.2.3 on 2023-12-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_carro_placa_carro_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='nome_cliente',
            new_name='cpf_cliente',
        ),
        migrations.AddField(
            model_name='carro',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carro',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
