# Generated by Django 4.2.3 on 2023-12-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_nome_cliente_carro_cpf_cliente_carro_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='cpf_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.cliente'),
        ),
    ]
