# Generated by Django 4.2.3 on 2023-12-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_carro_cpf_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
