# Generated by Django 4.2.3 on 2023-12-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_carro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='estoque',
        ),
    ]
